"""add_courier_password_order_soft_delete_indexes

Revision ID: 3e03eb469807
Revises: 4b59c3322ed0
Create Date: 2026-07-19 02:59:18.352834
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e03eb469807'
down_revision: Union[str, None] = '4b59c3322ed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('couriers', sa.Column('hashed_password', sa.String(length=128), nullable=False, server_default=''))
    op.create_index(op.f('ix_couriers_phone'), 'couriers', ['phone'], unique=True)
    op.add_column('orders', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_orders_courier_id'), 'orders', ['courier_id'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_courier_id'), table_name='orders')
    op.drop_column('orders', 'is_deleted')
    op.drop_index(op.f('ix_couriers_phone'), table_name='couriers')
    op.drop_column('couriers', 'hashed_password')
    # ### end Alembic commands ###
