"""add admin_phone

Revision ID: 4b59c3322ed0
Revises: a49605622fd6
Create Date: 2026-07-15 18:13:53.126260
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b59c3322ed0'
down_revision: Union[str, None] = 'a49605622fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('admin_phone', sa.String(length=20), server_default='+79000000000', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'admin_phone')
    # ### end Alembic commands ###
