"""add recipient_phone

Revision ID: be1f957b9960
Revises: 5d22db407f6c
Create Date: 2026-07-14 20:05:41.399264
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be1f957b9960'
down_revision: Union[str, None] = '5d22db407f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('recipient_phone', sa.String(length=20), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'recipient_phone')
    # ### end Alembic commands ###
