"""add_cancel_reason_to_orders

Revision ID: d2e8fdbb4a50
Revises: 3e03eb469807
Create Date: 2026-07-19 03:08:24.660157
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2e8fdbb4a50'
down_revision: Union[str, None] = '3e03eb469807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('cancel_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'cancel_reason')
    # ### end Alembic commands ###
